/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockfishRouteImport } from './routes/stockfish'
import { Route as InternetRouteImport } from './routes/internet'
import { Route as IndexRouteImport } from './routes/index'

const StockfishRoute = StockfishRouteImport.update({
  id: '/stockfish',
  path: '/stockfish',
  getParentRoute: () => rootRouteImport,
} as any)
const InternetRoute = InternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internet': typeof InternetRoute
  '/stockfish': typeof StockfishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internet': typeof InternetRoute
  '/stockfish': typeof StockfishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internet': typeof InternetRoute
  '/stockfish': typeof StockfishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/internet' | '/stockfish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/internet' | '/stockfish'
  id: '__root__' | '/' | '/internet' | '/stockfish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternetRoute: typeof InternetRoute
  StockfishRoute: typeof StockfishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stockfish': {
      id: '/stockfish'
      path: '/stockfish'
      fullPath: '/stockfish'
      preLoaderRoute: typeof StockfishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet': {
      id: '/internet'
      path: '/internet'
      fullPath: '/internet'
      preLoaderRoute: typeof InternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternetRoute: InternetRoute,
  StockfishRoute: StockfishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
